apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "kubebot.name" .}}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "kubebot.labels" . | indent 4 }}
type: Opaque
data:
  token: {{ .Values.slack.token | b64enc }}