apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "kubebot.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "kubebot.labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
{{ include "kubebot.labels" . | indent 8 }}
    spec:
      {{- if .Values.rbac }}
      serviceAccountName: "{{ template "kubebot.name" . }}"
      {{- end }}
      containers:
      - name: kubebot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: KUBEBOT_SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ template "kubebot.name" . }}"
              key: token
        - name: KUBEBOT_SLACK_CHANNELS_IDS
          value: {{ join " " .Values.slack.channel_ids | quote }}
        - name: KUBEBOT_SLACK_ADMINS_NICKNAMES
          value: {{ join " " .Values.slack.admin_nicknames | quote }}
        - name: KUBEBOT_SLACK_VALID_COMMANDS
          value: {{ join " " .Values.commands | quote }}
